In [3]:
#Create a null vector of size 10 but the fifth value which is 1.
A=np.array([int(x==4) for x in range(10)])
print(A)

[0 0 0 0 1 0 0 0 0 0]


In [4]:
# Create a vector with values ranging from 10 to 49
B=np.arange(10,50)
print (B)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#Create a 3x3 matrix with values ranging from 0 to 8
C = np.arange(9).reshape(3,3)
print (C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
D = np.nonzero([1,2,0,0,4,0])
print(D)

(array([0, 1, 4], dtype=int64),)


In [7]:
#Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.01618189752318988 0.9973804788562962


In [8]:
#Create a random vector of size 30 and find the mean value
E = np.random.random(10)
m = E.mean()
print (m)

0.4371533290475905
